<?xml version="1.0" ?>
<wsdl:definitions targetNamespace="urn:gosa.wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:gosa.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/1999/XMLSchema">
    <wsdl:message name="addInput">
        <wsdl:part name="x" type="xsd:integer"/>
        <wsdl:part name="y" type="xsd:integer"/>
    </wsdl:message>
    <wsdl:message name="addOutput">
        <wsdl:part name="result" type="xsd:integer"/>
    </wsdl:message>
    <wsdl:portType name="addPortType">
        <wsdl:operation name="add">
            <wsdl:input message="addInput"/>
            <wsdl:output message="addOutput"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="addBinding" type="tns:addPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="add">
            <soap:operation soapAction="add"/>
            <wsdl:input>
                <soap:body namespace="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="addService">
        <wsdl:port binding="tns:addBinding" name="addPort">
            <soap:address location="http://oss.gonicus.de/command"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
