#!/usr/bin/env python2.6
# -*- coding: utf-8 -*-

from gosa.common.components.amqp_proxy import AMQPEventConsumer
from qpid.util import URL
from lxml import etree

# Event callback
def process(data):
    print(etree.tostring(data, pretty_print=True))

# Create event consumer
consumer = AMQPEventConsumer("amqps://admin:tester@localhost/org.gosa",
            xquery="""
                declare namespace f='http://www.gonicus.de/Events';
                let $e := ./f:Event
                return $e/f:PuppetReport
            """,
            callback=process)

# Main loop, process threads
try:
    while True:
        consumer.join()
except KeyboardInterrupt:
    del consumer
    exit(0)
