#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd gosa >/dev/null; then
      adduser --disabled-password  --quiet --system \
        --home /var/lib/gosa \
        --gecos "gosa-agent daemon account" --group gosa
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

if [ -x "/etc/init.d/gosa.agent" ]; then
        update-rc.d gosa.agent defaults >/dev/null
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d gosa.agent start || exit $?
        else
                /etc/init.d/gosa.agent start || exit $?
        fi
fi
