#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd gosa >/dev/null; then
      adduser --disabled-password  --quiet --system \
        --home /var/lib/gosa \
        --gecos "GOsa daemon account" --group gosa
    fi

    chmod o-rwx /var/lib/gosa || /bin/true
    chown gosa.gosa /var/lib/gosa || /bin/true
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#
