#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd gosa-client >/dev/null; then
      adduser --disabled-password  --quiet --system \
        --home /var/lib/gosa-client \
        --gecos "gosa-client daemon account" --group gosa-client
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

