#!/usr/bin/env python
# -*- coding: utf-8 -*-
import libvirt

def main():
    # Connect to vbox session
    conn = libvirt.open('vbox:///session')
    print conn.listDefinedDomains()
    dom = conn.lookupByName("vbox-guest")
    dom.undefine()

    conn.close()

if __name__ == '__main__':
    main()
