#!/usr/bin/env python2.6
# -*- coding: utf-8 -*-
import libvirt

def main():
    # Connect to vbox session
    conn = libvirt.open('vbox:///session')
    pool = conn.storagePoolLookupByName("default-pool")

    xmlVolume = """
<volume>
  <name>vbox.img</name>
  <key>/home/test/.VirtualBox/HardDisks/vbox.img</key>
  <allocation>0</allocation>
  <capacity>10485760</capacity>
  <target>
    <path>/home/test/.VirtualBox/HardDisks/vbox.img</path>
  </target>
</volume>
"""
    pool.createXML(xmlVolume, 0)
    conn.close()

if __name__ == '__main__':
    main()
